version: '3.6'

services:
  lambda-tester:
    build: .
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - dynamodb
  dynamodb:
    build:
      context: .
      dockerfile: devops/dynamodb-local/Dockerfile
